ecommerce/demo/urls.py
from django.contrib import admin
from django.urls import include, path

from . import views

app_name = "demo"

urlpatterns = [
    path("", views.home, name="home"),
    path("categories/", views.category, name="category"),
    path("product-by-categorie/<slug:category>/", views.products_by_category, name="product_by_category"),
    path("<slug:slug>", views.product_detail, name="product_detail"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('demo/', include('ecommerce.demo.urls', namespace='demo')),
]

ecommerce/demo/models.py
from django.db import models

# Create your models here.

ecommerce/demo/views.py
from django.contrib.postgres.aggregates import ArrayAgg
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render
from ecommerce.inventory import models


def home(request):
    return render(request, "base.html")


def category(request):
    data = models.Category.objects.annotate(Count("product")).order_by("-product__count")
    p = Paginator(data, 10)

    page_number = request.GET.get("page")
    page_obj = p.get_page(page_number)

    num_categories = models.Category.objects.count()

    return render(request, "categories.html", {"page_obj": page_obj, "num_category": num_categories})


def products_by_category(request, category):

    data = models.Product.objects.filter(category__name=category).values(
        "id",
        "name",
        "slug",
        "description",
        "category__name",
        "product__store_price",
        "product__sku",
        "product__product_inventory__units",
    )
    p = Paginator(data, 42)

    pager_number = request.GET.get("page")
    page_obj = p.get_page(pager_number)

    num_products = models.Product.objects.filter(category__name=category).count()

    return render(
        request, "product_by_category.html", {"page_obj": page_obj, "category": category, "num_product": num_products}
    )


def product_detail(request, slug):

    filter_arguments = []

    if request.GET:
        for value in request.GET.values():
            filter_arguments.append(value)

        obj = (
            models.ProductInventory.objects.filter(product__slug=slug)
            .filter(attribute_values__attribute_value__in=filter_arguments)
            .annotate(num_tags=Count("attribute_values"))
            .filter(num_tags=len(filter_arguments))
            .values(
                "sku",
                "weight",
                "store_price",
                "product__slug",
                "product__description",
                "product__name",
                "brand__name",
                "product__category__name",
                "product__category__slug",
                "product_inventory__units",
            )
            .annotate(field_a=ArrayAgg("attribute_values__attribute_value"))
            .get()
        )
    else:
        obj = (
            (
                models.ProductInventory.objects.filter(product__slug=slug)
                .filter(is_default=True)
                .values(
                    "sku",
                    "weight",
                    "store_price",
                    "product__slug",
                    "product__description",
                    "product__name",
                    "brand__name",
                    "product__category__name",
                    "product__category__slug",
                    "product_inventory__units",
                )
            )
            .annotate(field_a=ArrayAgg("attribute_values__attribute_value"))
            .get()
        )

    inventory_attr = (
        models.ProductInventory.objects.filter(product__slug=slug)
        .distinct()
        .values(
            "attribute_values__product_attribute__name",
            "attribute_values__attribute_value",
        )
    )

    type_attr = (
        models.ProductTypeAttribute.objects.filter(product_type__product_type__product__slug=slug)
        .distinct()
        .values(
            "product_attribute__name",
        )
    )

    return render(
        request, "product_detail.html", {"obj": obj, "inventory_attr": inventory_attr, "type_attr": type_attr}
    )

ecommerce/demo/templates/base.html
<!DOCTYPE html>
  <html>
    <head>
        <!-- Bootstrap5 -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>
        <div class="container-fluid">
            <div class="col s12">
                <nav class="navbar navbar-expand-sm navbar-light bg-light p-3 border m-3">
                    <div class="container-fluid">
                        <a class="navbar-brand" href="{% url 'demo:home' %}">Ecommerce Python</a>
                        <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="collapsibleNavId">
                            <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                                <li class="nav-item active">
                                    <a class="nav-link" href="">Produtos <span class="visually-hidden">(current)</span></a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'demo:category' %}">Categorias</a>
                                </li>
                                <li class="nav-item ">
                                    <a class="nav-link" href="#">Inventario</a>
                                </li>
                            </ul>
                            <form class="d-flex my-2 my-lg-0">
                                <input class="form-control me-sm-2" type="text" placeholder="o que voce procura? :)">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Pesquisar</button>
                            </form>
                        </div>
                    </div>
                </nav>     
            </div>

            {% block content %}{% endblock content %}

        </div>
        
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

    </body>
  </html>

ecommerce/demo/templates/categories.html
{% extends 'base.html' %}

{% block content %}


    <div class="container-fluid">
        <div class="row">
            <div class="col col-sm-6">
                <p class="text-start fs-3">Categorias</p>
            </div>

            <div class="col col-sm-6">
                <p class="text-end fw-light">{{ page_obj.start_index}}-{{ page_obj.end_index }} de {{ num_category }}</p>
            </div>
        </div>
    </div>

    

    <div class="container-fluid">
        <div class="list-group"> 
            {% for i in page_obj %}
                <a {% if i.product__count > 0 %} class="list-group-item list-group-item-action" href="{% url 'demo:product_by_category' category=i.slug %}" {% else %}  class="list-group-item list-group-item-action disabled" href=""{% endif %} >
                    <div class="d-flex w-100 justify-content-between">
                        <h6 class="mb-1">{{i.name|upper}}</h6>
                        <span class="badge bg-primary rounded-pill">{{ i.product__count }}</span>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

    <nav class="container-fluid">
        <ul class="pagination justify-content-center m-3">
            
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}"><span aria-hidden="true">&laquo;</span></a>
                </li>
            {% else %}
                <li class="page-item desable">
                    <a class="page-link" href=""><span aria-hidden="true">&laquo;</span></a>
                </li>
            {% endif %}
            
            {% for i in page_obj.paginator.page_range %}
                <li {% if page_obj.number == i %} class="page-item active" {% else %} class="page-item" {% endif %}>
                    <a class="page-link" href="?page={{i}}">{{i}}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number}}"><span aria-hidden="true">&raquo;</span></a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href=""><span aria-hidden="true">&raquo;</span></a>
                </li>
            {% endif %}   
        </ul>
    </nav>


{% endblock content %}

ecommerce/demo/templates/index.html
{% extends 'base.html' %}

{% block content %}

    

{% endblock content %}

    

ecommerce/demo/templates/product_by_category.html
{% extends 'base.html' %}

{% block content %}
    
    <div class="container-fluid">
        <div class="row">
            <div class="col col-sm-6">
                <p class="text-start fs-3">{{ category|upper }}</p>
            </div>
            <div class="col col-sm-6">
                <p class="text-end fw-light">{{ page_obj.start_index}}-{{ page_obj.end_index }} de {{ num_product }}</p>
            </div>
        </div>
    </div>

    <div class="row">
        {% for i in page_obj %}
            <div class="col col-sm-3 col-lg-2">
                <div class="card border m-3">
                    <img class="card-img-top" src="https://mapbiomas.org/assets/camaleon_cms/image-not-found-4a963b95bf081c3ea02923dceaeb3f8085e1a654fc54840aac61a57a60903fef.png">
                    <div class="card-body">
                        <p class="card-title fw-blod lh-1">{{ i.name|slice:":20"|upper }}</p>
                        <p>SKU: {{i.product__sku }}</p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-cente">R$ {{ i.product__store_price }}<a href="{% url 'demo:product_detail' slug=i.slug %}" class="btn btn-sm btn-primary"><i class="bi bi-cart-plus"></i></a></li>
                        
                    </ul>
                    <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-success">
                        {{ i.product__product_inventory__units }}
                    </span>
                </div>
            </div>
        {% endfor %}
    </div>

    <nav class="">
        <ul class="pagination justify-content-center m-3">
            
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.previous_page_number}}"><span aria-hidden="true">&laquo;</span></a>
                </li>
            {% else %}
                <li class="page-item desable">
                    <a class="page-link" href=""><span aria-hidden="true">&laquo;</span></a>
                </li>
            {% endif %}
            
            {% for i in page_obj.paginator.page_range %}
                <li {% if page_obj.number == i %} class="page-item active" {% else %} class="page-item" {% endif %}>
                    <a class="page-link" href="?page={{i}}">{{i}}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{page_obj.next_page_number}}"><span aria-hidden="true">&raquo;</span></a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href=""><span aria-hidden="true">&raquo;</span></a>
                </li>
            {% endif %}   
        </ul>
    </nav>

{% endblock content %}

ecommerce/demo/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
        <div class="col col-sm-6">
            <nav class="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{% url 'demo:home' %}">HOME</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'demo:category' %}">CATEGORIAS</a></li>
                    <li class="breadcrumb-item"><a href="{% url 'demo:product_by_category' category=obj.product__category__slug %}">{{ obj.product__category__name|upper }}</a></li>
                </ol>
            </nav>
        </div>
        </div>
        <div class="row">
        <div class="col col-sm-6">
            <p class="display-5 text-start fw-bold">{{ obj.product__name|upper }}</p>
            <p class="fs-6 text-start fw-lighter">SKU: {{ obj.sku }}</p>
        </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="row m-3">
            <div class="col col-sm-6">
                <img src="https://mapbiomas.org/assets/camaleon_cms/image-not-found-4a963b95bf081c3ea02923dceaeb3f8085e1a654fc54840aac61a57a60903fef.png" class="rounded float-start" alt="...">
            </div>
            <div class="col col-sm-6">
                <p class="display-6 fw-bolder">R$ {{ obj.store_price }}</p>
                <p>Peso: {{ obj.weight }}g</p>
                <p>Marca: {{ obj.brand__name|upper }}</p>
                <div class="col col-sm-12">
                {% for i in type_attr %}
                    <p class="mb-2">{{i.product_attribute__name|upper}}:</p>
                    {% for j in inventory_attr %}
                        {% if j.attribute_values__product_attribute__name == i.product_attribute__name %}    
                            <div class="btn-group" role="group" aria-label="Basic example">
                            {% if j.attribute_values__attribute_value in obj.field_a %}
                                <button type="button" id="target-{{j.attribute_values__attribute_value}}" class="selected btn btn-outline-dark active" data-attribute="{{i.product_attribute__name}}" value="{{j.attribute_values__attribute_value}}">{{ j.attribute_values__attribute_value|upper }}</button>
                            {% else %}
                                <button type="button" id="target-{{j.attribute_values__atribute_value}}" class="btn btn-outline-dark" data-attribute="{{i.product_attribute__name}}" value="{{j.attribute_values__attribute_value}}">{{ j.attribute_values__attribute_value|upper }}</button>                                
                            {% endif %}
                            </div>                          
                        {% endif %}
                    {% endfor %} 
                {% endfor %}
                </div>
                <div class="d-grid gap-2 mt-4">
                    <button class="btn btn-success btn-lg">COMPRAR</button>
                </div>
            </div>
        </div>
    </div>

    <script>
        var d = {}

        let textBoxes = document.querySelectorAll('[id^=target]');

        let e = 0
        let f = textBoxes.length

        for (let i in textBoxes) {
            if (e < f) {
            if (textBoxes[i].classList.contains("selected")) {
                d[textBoxes[i].getAttribute('data-attribute')] = textBoxes[i].getAttribute('value')
            }
            } else {
            break
            }
            e++
        }

        document.addEventListener('click', function(e) {
        let value = e.target.getAttribute('value');
        d[e.target.getAttribute('data-attribute')] = e.target.getAttribute('value')
        let querystring = buildUrlWithParams(d)
        let url = window.location.href.split('?')[0]
        window.location.href = url + "?" + querystring;
        }, false);



        function buildUrlWithParams(data) {
            var searchparams = [];
            for (var d in data)
            searchparams.push(d + '=' + data[d]);
            return searchparams.join('&');
        }
    </script>

{% endblock content %}